"""Excel report (openpyxl): session records, per-student and per-subject summaries."""
from __future__ import annotations

from io import BytesIO

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from core import config
from core.access import Actor
from reports.common import ReportFilters, build, date_range_label

HEADER_FILL = PatternFill("solid", fgColor="1C5CAB")
LOW_FILL = PatternFill("solid", fgColor="F8D7D7")


def _write_sheet(ws, title_lines: list[str], df: pd.DataFrame, pct_col: str | None = None) -> None:
    for i, line in enumerate(title_lines, start=1):
        ws.cell(row=i, column=1, value=line).font = Font(bold=(i == 1), size=13 if i == 1 else 10)
    start = len(title_lines) + 2
    if df.empty:
        ws.cell(row=start, column=1, value="No records for the selected filters.")
        return
    for j, col in enumerate(df.columns, start=1):
        c = ws.cell(row=start, column=j, value=str(col).replace("_", " ").title())
        c.font, c.fill = Font(bold=True, color="FFFFFF"), HEADER_FILL
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thr = float(config.get("attendance.required_percentage", 75))
    for i, row in enumerate(df.itertuples(index=False), start=start + 1):
        for j, v in enumerate(row, start=1):
            ws.cell(row=i, column=j, value=None if (isinstance(v, float) and pd.isna(v)) else v)
        if pct_col is not None:
            v = getattr(row, pct_col)
            if v < thr:
                for j in range(1, len(df.columns) + 1):
                    ws.cell(row=i, column=j).fill = LOW_FILL
    for j, col in enumerate(df.columns, start=1):
        width = max(len(str(col)), *(len(str(v)) for v in df[col].head(300))) + 2
        ws.column_dimensions[get_column_letter(j)].width = min(width, 45)
    ws.freeze_panes = ws.cell(row=start + 1, column=1)
    ws.auto_filter.ref = f"A{start}:{get_column_letter(len(df.columns))}{start + len(df)}"


def generate(actor: Actor, filters: ReportFilters) -> bytes:
    d = build(actor, filters)
    inst = config.get("institution.name")
    head = [f"{inst} - Attendance Report",
            f"Subject: {d.subject_label}   |   Student: {d.student_label}",
            f"Period: {date_range_label(d.filters)}   |   Generated by {d.generated_by} on {d.generated_at}",
            f"Required attendance: {config.get('attendance.required_percentage')}%   |   "
            f"Late weight: {config.get('attendance.late_weight')}   (rows below the threshold are highlighted)"]

    rec = d.records
    if not rec.empty:
        rec = rec[["date", "start_time", "subject_code", "roll_no", "full_name", "status", "check_in_time",
                   "source", "match_distance", "liveness_score", "failed_attempts"]].copy()
        rec["status"] = rec["status"].str.title()
    stu = d.students.drop(columns=["user_id"]) if not d.students.empty else d.students
    subj = d.subjects.drop(columns=["subject_id"]) if not d.subjects.empty else d.subjects
    ss = (d.student_subjects.drop(columns=["user_id", "subject_id"])
          if not d.student_subjects.empty else d.student_subjects)

    wb = Workbook()
    ws = wb.active
    ws.title = "Session records"
    _write_sheet(ws, head, rec)
    _write_sheet(wb.create_sheet("Student summary"), head, stu, "attendance_pct")
    _write_sheet(wb.create_sheet("Subject summary"), head, subj)
    _write_sheet(wb.create_sheet("Student x subject"), head, ss, "attendance_pct")
    if not d.risk.empty:
        risk = d.risk[["roll_no", "full_name", "code", "probability", "level", "method", "model_version"]].copy()
        risk["key_factors"] = d.risk["top_factors"].map(lambda fs: "; ".join(f"{x['label']}: {x['value']}" for x in fs))
        _write_sheet(wb.create_sheet("Risk"), head, risk)
    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
